// <auto-generated />
using System;
using HRAssistant.Web.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRAssistant.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRAssistant.Web.Domain.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.FormEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("VacancyId");

                    b.HasKey("Id");

                    b.ToTable("Form");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.JobPositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("TemplateId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.ToTable("JobPosition");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.OptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsCorrect");

                    b.Property<Guid>("QuestionId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.QuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<Guid?>("FormId");

                    b.Property<int>("OrderIndex");

                    b.Property<Guid?>("TemplateId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Question");

                    b.HasDiscriminator<string>("Discriminator").HasValue("QuestionEntity");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CityId");

                    b.Property<bool>("IsBlocked");

                    b.Property<Guid>("TeamLeadId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TeamLeadId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.TemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsBlocked");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.VacancyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CandidateRequirements");

                    b.Property<Guid>("FormId");

                    b.Property<Guid>("JobPositionId");

                    b.Property<int?>("JobsNumber");

                    b.Property<decimal?>("Salary");

                    b.Property<int>("Status");

                    b.Property<Guid>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("FormId")
                        .IsUnique();

                    b.HasIndex("JobPositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.GeneralQuestionEntity", b =>
                {
                    b.HasBaseType("HRAssistant.Web.Domain.QuestionEntity");


                    b.ToTable("GeneralQuestion");

                    b.HasDiscriminator().HasValue("GeneralQuestionEntity");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.InputQuestionEntity", b =>
                {
                    b.HasBaseType("HRAssistant.Web.Domain.QuestionEntity");

                    b.Property<string>("CorrectAnswer");

                    b.ToTable("InputQuestionEntity");

                    b.HasDiscriminator().HasValue("InputQuestionEntity");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.SelectQuestionEntity", b =>
                {
                    b.HasBaseType("HRAssistant.Web.Domain.QuestionEntity");

                    b.Property<bool>("OneCorrectAnswer");

                    b.ToTable("SelectQuestionEntity");

                    b.HasDiscriminator().HasValue("SelectQuestionEntity");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.JobPositionEntity", b =>
                {
                    b.HasOne("HRAssistant.Web.Domain.TemplateEntity", "Template")
                        .WithOne("JobPosition")
                        .HasForeignKey("HRAssistant.Web.Domain.JobPositionEntity", "TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.OptionEntity", b =>
                {
                    b.HasOne("HRAssistant.Web.Domain.SelectQuestionEntity", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.QuestionEntity", b =>
                {
                    b.HasOne("HRAssistant.Web.Domain.FormEntity", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId");

                    b.HasOne("HRAssistant.Web.Domain.TemplateEntity", "Template")
                        .WithMany("Questions")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.TeamEntity", b =>
                {
                    b.HasOne("HRAssistant.Web.Domain.CityEntity", "City")
                        .WithMany("Teams")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HRAssistant.Web.Domain.UserEntity", "TeamLead")
                        .WithMany("TeamLeadTeams")
                        .HasForeignKey("TeamLeadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HRAssistant.Web.Domain.VacancyEntity", b =>
                {
                    b.HasOne("HRAssistant.Web.Domain.FormEntity", "Form")
                        .WithOne("Vacancy")
                        .HasForeignKey("HRAssistant.Web.Domain.VacancyEntity", "FormId")
                        .HasPrincipalKey("HRAssistant.Web.Domain.FormEntity", "VacancyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HRAssistant.Web.Domain.JobPositionEntity", "JobPosition")
                        .WithMany("Vacancies")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HRAssistant.Web.Domain.TeamEntity", "Team")
                        .WithMany("Vacancies")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
